// slip-export.jsx — Salary slip PDF export dengan canvas drawing

function SlipExportDialog({ employee, history, config, onClose }) {
  const [format, setFormat] = useState('preview'); // 'preview' | 'download'
  const stats = useMemo(() => {
    const totalLate = history.reduce((s, d) => s + d.late, 0);
    const totalPenalty = history.reduce((s, d) => s + d.penalty, 0);
    const onTime = history.filter(d => d.status === 'tepat').length;
    const lateDays = history.filter(d => d.late > 0).length;
    const spDays = history.filter(d => d.status === 'sp').length;
    return { totalLate, totalPenalty, onTime, lateDays, spDays };
  }, [history]);

  const baseSalary = employee.baseSalary || 3200000;
  const conduct = CONDUCT_HISTORY[employee.id] || { adjustments: [] };
  const totalReductions = conduct.adjustments.reduce((s, a) => s + a.reduction, 0);
  const finalPenalty = Math.max(0, stats.totalPenalty - totalReductions);
  const net = baseSalary - finalPenalty;

  const downloadPDF = async () => {
    // Simple canvas-based PDF generation
    const canvas = createCanvas(595, 842); // A4 size
    const ctx = canvas.getContext('2d');

    // Background
    ctx.fillStyle = '#F4F1EA';
    ctx.fillRect(0, 0, 595, 842);

    // Text colors
    ctx.fillStyle = '#0A0A0A';
    ctx.font = 'bold 18px "Instrument Serif"';
    ctx.fillText('D\'AJIKS COFFEE & BILLIARD', 40, 40);
    ctx.font = 'italic 14px "Instrument Serif"';
    ctx.fillText('SLIP GAJI', 40, 65);

    // Divider
    ctx.strokeStyle = 'rgba(0,0,0,0.15)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(40, 80);
    ctx.lineTo(555, 80);
    ctx.stroke();

    // Employee info
    ctx.font = '12px "JetBrains Mono"';
    ctx.fillStyle = 'rgba(0,0,0,0.6)';
    ctx.fillText('KARYAWAN', 40, 105);
    ctx.font = 'bold 13px -apple-system, sans-serif';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText(employee.name, 40, 125);
    ctx.font = '11px "JetBrains Mono"';
    ctx.fillStyle = 'rgba(0,0,0,0.5)';
    ctx.fillText(`${employee.id} · BARISTA · SHIFT 1`, 40, 140);

    // Period
    ctx.font = '12px "JetBrains Mono"';
    ctx.fillStyle = 'rgba(0,0,0,0.6)';
    ctx.fillText('PERIODE', 400, 105);
    ctx.font = 'bold 13px "JetBrains Mono"';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText('01 — 31 MEI 2026', 400, 125);

    let y = 170;

    // Main calculation
    ctx.font = '12px -apple-system, sans-serif';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText('Gaji pokok', 40, y);
    ctx.font = 'bold 12px "JetBrains Mono"';
    ctx.textAlign = 'right';
    ctx.fillText(`Rp ${baseSalary.toLocaleString('id-ID')}`, 555, y);
    ctx.textAlign = 'left';

    y += 20;
    ctx.font = '12px -apple-system, sans-serif';
    ctx.fillStyle = 'rgba(204,87,46,1)';
    ctx.fillText(`Potongan telat (${stats.totalLate}m × Rp ${config.penaltyPerMinute.toLocaleString('id-ID')})`, 40, y);
    ctx.font = 'bold 12px "JetBrains Mono"';
    ctx.textAlign = 'right';
    ctx.fillText(`−Rp ${stats.totalPenalty.toLocaleString('id-ID')}`, 555, y);
    ctx.textAlign = 'left';

    if (totalReductions > 0) {
      y += 20;
      ctx.font = '12px -apple-system, sans-serif';
      ctx.fillStyle = 'rgba(85,170,100,1)';
      ctx.fillText('Keringanan (performa baik)', 40, y);
      ctx.font = 'bold 12px "JetBrains Mono"';
      ctx.textAlign = 'right';
      ctx.fillStyle = 'rgba(85,170,100,1)';
      ctx.fillText(`+Rp ${totalReductions.toLocaleString('id-ID')}`, 555, y);
      ctx.textAlign = 'left';
    }

    // Divider line
    y += 20;
    ctx.strokeStyle = 'rgba(0,0,0,0.15)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(40, y);
    ctx.lineTo(555, y);
    ctx.stroke();

    // Total
    y += 20;
    ctx.font = 'italic 14px "Instrument Serif"';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText('GAJI BERSIH', 40, y);
    ctx.font = 'bold 16px "JetBrains Mono"';
    ctx.textAlign = 'right';
    ctx.fillText(`Rp ${net.toLocaleString('id-ID')}`, 555, y);
    ctx.textAlign = 'left';

    // Summary
    y += 50;
    ctx.font = '12px "JetBrains Mono"';
    ctx.fillStyle = 'rgba(0,0,0,0.6)';
    ctx.fillText('RINGKASAN DISIPLIN BULAN INI', 40, y);

    y += 20;
    ctx.font = '11px -apple-system, sans-serif';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText(`• Hari tepat waktu: ${stats.onTime} hari`, 60, y);
    y += 15;
    ctx.fillText(`• Hari telat: ${stats.lateDays} hari (${stats.totalLate}m total)`, 60, y);
    y += 15;
    ctx.fillText(`• SP diterbitkan: ${stats.spDays > 0 ? `${stats.spDays} SP` : 'Tidak ada'}`, 60, y);

    // Footer
    y = 750;
    ctx.font = '10px "JetBrains Mono"';
    ctx.fillStyle = 'rgba(0,0,0,0.4)';
    ctx.textAlign = 'center';
    ctx.fillText('Document generated by D\'AJIKS · Attendance System v1.0', 297.5, y);
    ctx.fillText(`${new Date().toLocaleDateString('id-ID')}`, 297.5, y + 15);

    // Convert to blob & trigger download
    canvas.toBlob((blob) => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Slip_${employee.name.replace(/\s+/g, '_')}_Mei2026.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    });
  };

  return (
    <div style={{
      position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 1000,
      display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <Ticket padding={24} style={{
        background: TOKENS.card, maxWidth: 500, maxHeight: '90vh', overflowY: 'auto',
        borderRadius: 8,
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <Eyebrow>SLIP GAJI</Eyebrow>
          <button onClick={onClose} style={{
            background: 'transparent', border: 'none', fontSize: 18, cursor: 'pointer',
          }}>✕</button>
        </div>

        <div style={{ fontFamily: TOKENS.fontDisplay, fontSize: 22, fontStyle: 'italic', marginBottom: 16 }}>
          {employee.name}
        </div>

        <div style={{ padding: 14, background: TOKENS.paper, borderRadius: 4, marginBottom: 14 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, marginBottom: 8 }}>
            <span>Gaji pokok</span>
            <span className="mono" style={{ fontWeight: 600 }}>{fmtRupiah(baseSalary)}</span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, marginBottom: 8 }}>
            <span>Potongan telat</span>
            <span className="mono" style={{ fontWeight: 600, color: TOKENS.late }}>−{fmtRupiah(stats.totalPenalty)}</span>
          </div>
          {totalReductions > 0 && (
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, marginBottom: 8 }}>
              <span>Keringanan</span>
              <span className="mono" style={{ fontWeight: 600, color: TOKENS.ontime }}>+{fmtRupiah(totalReductions)}</span>
            </div>
          )}
          <div style={{
            borderTop: `1px solid ${TOKENS.ink15}`, paddingTop: 8, marginTop: 8,
            display: 'flex', justifyContent: 'space-between', fontSize: 14, fontWeight: 700,
          }}>
            <span>Gaji bersih</span>
            <span className="mono">{fmtRupiah(net)}</span>
          </div>
        </div>

        <div style={{ padding: 12, background: TOKENS.ink04, borderRadius: 4, marginBottom: 16 }}>
          <div style={{ fontSize: 12, fontFamily: TOKENS.fontMono, color: TOKENS.ink70, lineHeight: 1.6 }}>
            Telat {stats.totalLate}m ({stats.lateDays} hari) × Rp {SYSTEM_CONFIG.penaltyPerMinute.toLocaleString('id-ID')}/menit
            {totalReductions > 0 && <br/>}
            {totalReductions > 0 && `Dikurangi Rp ${totalReductions.toLocaleString('id-ID')} karena performa baik`}
          </div>
        </div>

        <div style={{ display: 'flex', gap: 8 }}>
          <button onClick={() => onClose()} style={{ ...btnGhost, flex: 1 }}>Tutup</button>
          <button onClick={downloadPDF} style={{ ...btnSolid, flex: 1 }}>Unduh PDF →</button>
        </div>
      </Ticket>
    </div>
  );
}

// Helper: create canvas
function createCanvas(w, h) {
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return c;
}

Object.assign(window, { SlipExportDialog });
